### ISSUE TITLE
Please update the ARCore

### ISSUE THREAD

**Issue by Zumbalamambo** [NON906/HandMR#1]
It is not working with the latest version of ARCore

**Comment by NON906** [comment]
Please try to run "HandMR->Android->Initialize Scene with VR" on empty scene.
(This is resetting prefab. It probably fix.)

**Comment by NON906** [comment]
I add "HandMR->Android->Initialize Prefabs with VR" in 0979c87a8badfbdc8ee85e509408d58ed9d608d1.
Please pull and run this.

**Comment by Zumbalamambo** [comment]
@NON906 thank you! Could you please tell me where I must place the aar files? It always says class can not be found and also it is not able to load the so file :(

**Comment by NON906** [comment]
You can download and place by running "HandMR->Android->Download Assets and Init Project with MR" and "HandMR->Android->Download Assets and Init Project with VR".

If you prepare manually, please download the following:
- https://github.com/google-ar/arcore-unity-sdk/releases/download/v1.15.0/arcore-unity-sdk-1.15.0.unitypackage
- https://github.com/ho-lo/HologlaSDK-Unity/releases/download/v0.9.0-beta/Hologla.unitypackage

And add packages in "Window->Package Manager" the following:
- com.unity.xr.legacyinputhelpers
- com.unity.multiplayer-hlapi
- com.unity.xr.googlevr.android

**Comment by NON906** [comment]
I close this issue because this is old and no reply.
Please contact me again if necessary.
