### ISSUE TITLE
サンプルシーンについてお教え下さい。

### ISSUE THREAD

**Issue by cocosdaison** [NON906/HandMR#3]
お久しぶりです。以前ビルド時のエラーについて質問させていただいた者です。

公開してくださっているサンプルシーンについての質問です。このシーン内でボタンとスライダーが実装されていますが、これらの接触判定をどのように行なっているかお教え下さい。見たところUI側にはスクリプトが設定されておらず、hand側にもcolliderが付いていなかったため、仕組みがわかりませんでした。

抽象的な質問になってしまい申し訳ありません。お答えいただけると幸いです。

**Comment by NON906** [comment]
分かりづらくてすいません。
HandMRManagerオブジェクトにアタッチされている、「HandMRInputModule.cs」というスクリプトでUIの処理を行っています。

**Comment by cocosdaison** [comment]
返信ありがとうございます。
了解しました。当該スクリプトの内容を理解するようにいたします。
