### ISSUE TITLE
Unable to download ios plugins.

### ISSUE THREAD

**Issue by jerryComo** [NON906/HandMR#7]
Android plug-in downloads fine off the dialogue. But when I select download plug-in it begins download, then never completes. 
Have tried this on 2020 and 2021 LTS versions.

As a result the plug-in never appears in the build xcode project.

**Comment by NON906** [comment]
Excuse me, how did you install this asset (git clone, unitypackage or Asset Store)?

**Comment by jerryComo** [comment]
Hi - I've tried it through the Asset Store and also the unitypackage from the link posted here. 

I get this error when trying to install from the git URL in packagemanager
[Package Manager Window] Unable to add package [git@github.com:NON906/HandMR.git]:
  Error when executing git command. ssh: connect to host github.com port 22: Network is unreachable
  fatal: Could not read from remote repository.

**Comment by NON906** [comment]
There is a problem that the progress bar does not close, but the file itself seems to be imported.
Please check if files exist as shown in the image, put a check OpenGLES and try again.

![screenshot](https://user-images.githubusercontent.com/30926385/194873905-d7feaa48-6f0d-436e-b4fa-e501a722ffe9.png)

Please note that this repository does not support Package Manager, so please use unitypackage or Asset Store.

**Comment by jerryComo** [comment]
that has fixed it - many thanks :)
